export { default as LandingPage } from './LandingPage'
export { default as NotFound } from './404'
export { default as Biodata } from './Biodata'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Profile } from './Profile'
