export { default as AdminLogin } from './AdminLogin'
export { default as Dashboard } from './Dashboard'
export { default as Biodata } from './Biodata'
export { default as EditBiodata } from './EditBiodata'
export { default as Image } from './Image'